[package]
name = "core-math-sys"
version = "1.2.0"
links = "core_math"
authors = ["Chen-Pang He (https://jdh8.org)"]
edition = "2024"
rust-version = "1.85"
description = "Generate bindings to CORE-MATH"
repository = "https://github.com/jdh8/core-math-sys"
license = "MIT"
categories = ["mathematics", "no-std"]
keywords = ["floating-point", "trigonometry", "exponential", "logarithm", "special-functions"]
exclude = ["/vendor/**/*.wc", "/vendor/doc"]

[features]
f16 = []
f128 = []

[package.metadata.docs.rs]
all-features = true

[profile.dev]
opt-level = 3

[build-dependencies]
bindgen = "0.72"
cc = { version = "1.2", features = ["parallel"] }
